### ISSUE TITLE
Impersonate user role

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/amaferm-research-backoffice#11]
What would it take to allow

Ming He
http://amafermresearch.backofficeapps.com/users/11 

Elishia Carrillo 

The ability to impoersonate different roles [Basic, Public sales, etc.]

**Comment by reed** [comment]
For what purpose?  To see less things?

**Comment by jamiemiller1486** [comment]
They are going to start having trainings with users and want to provide them exactly what they will see.

Jamie A Miller
Director of Research
LAN Resources, LLC
816-238-5596
www.lanresourcesllc.com<http://www.lanresourcesllc.com>
