### ISSUE TITLE
Users:  Export

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/amaferm-research-backoffice#14]
Please give Admins the ability to export the user list.

**Comment by reed** [comment]
Export to what?

**Comment by jamiemiller1486** [comment]
Excel [csv] or PDF

name
email
role

**Comment by reed** [comment]
I'm seeing that currently, all users are able to view the users page and view the entire user list, including what role they are.  That doesn't seem right to me.  Should this be changed?

**Comment by jamiemiller1486** [comment]
yeah that needs changed.  only Admins and Biozyme users should see users.

**Comment by reed** [comment]
In addition to those two roles, we also allow Basic Managers and Managers to add users.  If they can add users, they should probably be able to view them as well.  I can restrict them to just see users that are below them.  Does that work?
 
And who should be allowed to export users?

**Comment by jamiemiller1486** [comment]
Yes that works.

Just Admins can export
