### ISSUE TITLE
Download Tech Sheets

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/amaferm-research-backoffice#16]
Had an ASM call and said they were trying to share/send the Tech Sheet for one of the papers.

They all use iPads.  She was using Chrome Browser.  When she clicked on the the Download Tech Sheet icon it opened the pdf in a new window, she was not able to save it anywhere to send to a dealer, nor can she send the link because it will ask them to login to the site.

The one we were trying was http://amafermresearch.backofficeapps.com/papers/169/ which is set to Public

Any ideas on how to best share the tech sheets with someone via a mobile device.

**Comment by reed** [comment]
When I open the pdf in chrome and then tap on it, it brings up a link on the bottom that says "OPEN IN...":

![image](https://cloud.githubusercontent.com/assets/672142/24013969/29d1cf5a-0a51-11e7-9188-4f6c2233ed17.png)

Select that and it will bring up options.  Choose to add it to iCloud Drive.  Then compose an email and you'll be able to add it as an attachment.
