### ISSUE TITLE
INTL: Support Materials:  Domestic/International 

### ISSUE THREAD

**Issue by jamiemiller1486** [LANResources/amaferm-research-backoffice#18]
We are pushing Support Materials [Sales Aids] from Amaferm Research into the Partner Center.

Based on a meeting with the International Team last week, some of those items should for both Internal Partners and Domestic Partners and other only need to show for One or the other.

Need to add a check box option under Access that lets admins select Domestic and International

![image](https://user-images.githubusercontent.com/1561832/52541396-14284200-2d5a-11e9-8c8f-9da7097c2bb9.png)

If International is not checked, then those items should not show up in Support Materials for International Partners and vice versa.

Also just a tweak, when you edit a Sales Aid item and then hit Save you go back to http://amafermresearch.backofficeapps.com/learn-more can you please set so you go back to http://amafermresearch.backofficeapps.com/sales_aids/manage

**Comment by jamiemiller1486** [comment]
We need to change these to act just like products in the Back Office where we can assign countries to Each Sales Aid and then those would show in the partner center based on the Partner's country of origin.

**Comment by reed** [comment]
So a sales aid should have a single country or multiple countries assigned to it?

**Comment by jamiemiller1486** [comment]
Multple
________________________________

**Comment by reed** [comment]
Do you still need the international/domestic toggle?

**Comment by jamiemiller1486** [comment]
Not if we do the countries

**Comment by reed** [comment]
Added country support.  Once you get them all updated, I'll work on adding the restrictions to the partner center.
